export default function especiesBeneficios(codigo) {
    let lista = {
        "07": "Aposentadoria por idade do trabalhador rural",
        "08": "Aposentadoria por idade do empregador rural",
        "41": "Aposentadoria por idade",
        "52": "Aposentadoria por idade(Extinto Plano Básico)",
        "78": "Aposentadoria por idade de ex- combatente marítimo (Lei nº 1.756 / 52) ",
        "81": " Aposentadoria por idade compulsória(Ex - SASSE)",
        "04": "Aposentadoria por invalidez do trabalhador rural",
        "06": "Aposentadoria por invalidez do empregador rural",
        "32": "Aposentadoria por invalidez previdenciária",
        "33": "Aposentadoria por invalidez de aeronauta",
        "34": "Aposentadoria por invalidez de ex - combatente marítimo(Lei nº 1.756 / 52)",
        "51": " Aposentadoria por invalidez(Extinto Plano Básico)",
        "83": "Aposentadoria por invalidez(Ex - SASSE)",
        "42": "Aposentadoria por tempo de contribuição previdenciária",
        "43": " Aposentadoria por tempo de contribuição de ex - combatente",
        "44": " Aposentadoria por tempo de contribuição de aeronauta",
        "45": "Aposentadoria por tempo de contribuição de jornalista profissional",
        "46": "Aposentadoria por tempo de contribuição especial",
        "49": "Aposentadoria por tempo de contribuição ordinária",
        "57": "Aposentadoria por tempo de contribuição de professor(Emenda Const.18 / 81)",
        "72": " Apos.por tempo de contribuição de ex - combatente marítimo(Lei 1.756 / 52)",
        "82": "Aposentadoria por tempo de contribuição(Ex - SASSE)",
        "01": "Pensão por morte do trabalhador rural",
        "03": "Pensão por morte do empregador rural",
        "21": "Pensão por morte previdenciária",
        "23": "Pensão por morte de ex - combatente",
        "27": "Pensão por morte de servidor público federal com dupla aposentadoria",
        "28": "Pensão por morte do Regime Geral(Decreto nº 20.465 / 31)",
        "29": "ensão por morte de ex - combatente marítimo(Lei nº 1.756 / 52)",
        "55": " Pensão por morte(Extinto Plano Básico)",
        "84": " Pensão por morte(Ex - SASSE)",
        "13": "Auxílio - doença do trabalhador rural",
        "15": "Auxílio - reclusão do trabalhador rural",
        "25": "Auxílio - reclusão",
        "31": "Auxílio - doença previdenciário",
        "36": "Auxílio Acidente",
        "50": "Auxílio - doença(Extinto Plano Básico)",
        "02": "Pensão por morte por acidente do trabalho do trabalhador rural",
        "05": "Aposentadoria por invalidez por acidente do trabalho do trabalhador Rural",
        "10": "Auxílio - doença por acidente do trabalho do trabalhador rural",
        "91": "Auxílio - doença por acidente do trabalho",
        "92": "Aposentadoria por invalidez por acidente do trabalho",
        "93": "Pensão por morte por acidente do trabalho",
        "94": "Auxílio - acidente por acidente do trabalho",
        "95": "Auxílio - suplementar por acidente do trabalho",
        "11": " Renda mensal vitalícia por invalidez do trabalhador rural(Lei nº 6.179 / 74)",
        "12": "Renda mensal vitalícia por idade do trabalhador rural(Lei nº 6.179 / 74)",
        "30": "Renda mensal vitalícia por invalidez(Lei nº 6179 / 74)",
        "40": "Renda mensal vitalícia por idade(Lei nº 6.179 / 74)",
        "85": " Pensão mensal vitalícia do seringueiro(Lei nº 7.986 / 89)",
        "86": "Pensão mensal vitalícia do dep.do seringueiro(Lei nº 7.986 / 89)",
        "87": "Amparo assistencial ao portador de deficiência(LOAS)",
        "88": " Amparo assistencial ao idoso(LOAS)",
        "47": "Abono de permanência em serviço 25 %",
        "48": "Abono de permanência em serviço 20 %",
        "68": " Pecúlio especial de aposentadoria",
        "79": "Abono de servidor aposentado pela autarquia empr.(Lei 1.756 / 52)",
        "80": "Salário - maternidade",
        "22": "Pensão por morte estatutária",
        "26": " Pensão Especial(Lei nº 593 / 48)",
        "37": " Aposentadoria de extranumerário da União",
        "38": "Aposentadoria da extinta CAPIN",
        "54": "Pensão especial vitalícia(Lei nº 9.793 / 99)",
        "56": " Pensão mensal vitalícia por síndrome de talidomida(Lei nº 7.070 / 82)",
        "58": "Aposentadoria excepcional do anistiado(Lei nº 6.683 / 79)",
        "59": "Pensão por morte excepcional do anistiado(Lei nº 6.683 / 79)",
        "60": "Pensão especial mensal vitalícia(Lei 10.923, de 24 / 07 / 2004)",
        "76": "Salário - família estatutário da RFFSA(Decreto - lei nº 956 / 69)",
        "89": "Pensão especial aos depedentes de vítimas fatais p / contaminação na hemodiálise",
        "96": "Pensão especial às pessoas atingidas pela hanseníase(Lei nº 11.520 / 2007)"
    }
    return lista[codigo].toUpperCase()
}